"""empty message

Revision ID: 4c01eff99343
Revises: None
Create Date: 2016-05-03 22:26:00.649465

"""

# revision identifiers, used by Alembic.
revision = '4c01eff99343'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal')
    op.drop_table('tags')
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=128), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=128), nullable=False),
    sa.Column('username', sa.VARCHAR(length=128), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
    sa.Column('password', sa.VARCHAR(length=192), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('body', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('tags', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tags'], [u'tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
